# -*- MakeFile -*-

CC = gcc
CFLAGS = -Wall -g

all: ex7.1 ex7.2 ex7.3 ex7.4 ex7.5 ex7.6 ex7.7 ex7.8 ex7.9

ex7.1: ex7.1.c
	$(CC) $(CFLAGS) ex7.1.c -o ex7.1

ex7.2: ex7.2.c
	$(CC) $(CFLAGS) ex7.2.c -o ex7.2

ex7.3: ex7.3.c
	$(CC) $(CFLAGS) ex7.3.c -o ex7.3

ex7.4: ex7.4.c
	$(CC) $(CFLAGS) ex7.4.c -o ex7.4

ex7.5: ex7.5.c
	$(CC) $(CFLAGS) ex7.5.c -o ex7.5

ex7.6: ex7.6.c
	$(CC) $(CFLAGS) ex7.6.c -o ex7.6

ex7.7: ex7.7.c
	$(CC) $(CFLAGS) ex7.7.c -o ex7.7

ex7.8: ex7.8.c
	$(CC) $(CFLAGS) ex7.8.c -o ex7.8

ex7.9: ex7.9.c
	$(CC) $(CFLAGS) ex7.9.c -o ex7.9

clean:
	rm -v ex7.1 ex7.2 ex7.3 ex7.4 ex7.5 ex7.6 ex7.7 ex7.8 ex7.9
